version: '3'

services:
  nginx:
    image: tiangolo/nginx-rtmp:latest-2022-11-09
    container_name: nginx-ls
    restart: unless-stopped
    ports:
      - "8083:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  cloudflared:
      image: cloudflare/cloudflared:2022.10.0-amd64
      container_name: cloudflared-notuse-nginxls
      restart: unless-stopped