version: '2'

services:
  nginx:
    image: tiangolo/nginx-rtmp:latest-2022-11-09
    container_name: nginx-ls
    restart: unless-stopped
    ports:
      - "8083:8080"
      - "8084:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./hlstmp:/tmp/hls
