version: '3'

services:
  nginx:
      image: tiangolo/nginx-rtmp:latest-2022-11-09
      container_name: nginx
      restart: unless-stopped
      ports:
        - "8083:1935"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf